In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./input_data/inaugural_speeches.csv')

In [3]:
df.head(2)

,Name,Inaugural Address,Date,text
0,George Washington,First Inaugural Address,"Thursday, April 30, 1789",Fellow-Citizens of the Senate and of the House...
1,George Washington,Second Inaugural Address,"Monday, March 4, 1793",Fellow Citizens: I AM again called upon by th...

In [4]:
df.text[0][:100]

'Fellow-Citizens of the Senate and of the House of Representatives:  AMONG the vicissitudes incident '

### Pre-processing text

In [5]:
df['clean_text'] = df.text.str.replace('[^a-zA-Z]', ' ', regex=True)

In [6]:
df.clean_text = df.clean_text.str.lower()

In [7]:
df.clean_text = df.clean_text.str.replace('\s+', ' ', regex=True)

In [8]:
df.clean_text[0][:100]

'fellow citizens of the senate and of the house of representatives among the vicissitudes incident to'

### Extract info from text

In [9]:
df['char_count'] = df.clean_text.str.len()

In [10]:
df['word_count']  = df.clean_text.str.split().str.len()

In [11]:
df['avg_word_length'] = df.char_count/df.word_count

In [12]:
df['year'] = df.Date.str.extract('(\d{4})')

In [13]:
df_final = df[['Name', 'Date', 'clean_text', 'char_count', 'word_count', 'avg_word_length', 'year']]
df_final.head()

,Name,Date,clean_text,char_count,word_count,avg_word_length,year
0,George Washington,"Thursday, April 30, 1789",fellow citizens of the senate and of the house...,8503,1432,5.937849,1789
1,George Washington,"Monday, March 4, 1793",fellow citizens i am again called upon by the ...,775,135,5.740741,1793
2,John Adams,"Saturday, March 4, 1797",when it was first perceived in early times tha...,13605,2323,5.856651,1797
3,Thomas Jefferson,"Wednesday, March 4, 1801",friends and fellow citizens called upon to und...,9931,1736,5.720622,1801
4,Thomas Jefferson,"Monday, March 4, 1805",proceeding fellow citizens to that qualificati...,12680,2169,5.846012,1805

### CountVectorizer

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
vectorizer = CountVectorizer(min_df=0.2, max_df=0.8)

In [16]:
vectorizer.fit(df_final['clean_text'])

CountVectorizer(max_df=0.8, min_df=0.2)

In [17]:
vectorizer.get_feature_names_out()

array(['abiding', 'ability', 'able', 'about', 'above', 'abroad', 'accept',
       'accomplished', 'achieve', 'across', 'act', 'action', 'acts',
       'add', 'adequate', 'administration', 'adopted', 'advance',
       'advantage', 'affairs', 'afford', 'after', 'again', 'against',
       'age', 'ago', 'agriculture', 'aid', 'alike', 'almighty', 'almost',
       'alone', 'along', 'already', 'also', 'always', 'am', 'america',
       'american', 'americans', 'among', 'ancient', 'another', 'appear',
       'armed', 'arms', 'around', 'ask', 'assume', 'attempt', 'attention',
       'authority', 'avoid', 'away', 'back', 'balance', 'basis', 'bear',
       'because', 'become', 'beginning', 'being', 'belief', 'believe',
       'believed', 'belongs', 'benefit', 'benefits', 'best', 'better',
       'between', 'beyond', 'birth', 'bless', 'blessings', 'blood',
       'body', 'bonds', 'born', 'both', 'bound', 'branches', 'bring',
       'brought', 'build', 'burden', 'burdens', 'business', 'call',
       'called', 'came', 'cannot', 'capacity', 'capital', 'care', 'carry',
       'cause', 'centuries', 'century', 'certain', 'challenge', 'chance',
       'change', 'changes', 'character', 'cherish', 'chief', 'children',
       'choice', 'chosen', 'circumstances', 'citizen', 'citizenship',
       'civil', 'civilization', 'claim', 'class', 'clear', 'clearly',
       'close', 'come', 'command', 'commerce', 'committed', 'common',
       'communities', 'community', 'complete', 'concern', 'concerns',
       'condition', 'conditions', 'conduct', 'confidence', 'conflict',
       'congress', 'conscience', 'consequences', 'consider',
       'consideration', 'considered', 'constant', 'constantly',
       'constitution', 'constitutional', 'continent', 'continue',
       'continued', 'control', 'conviction', 'cooperation', 'cost',
       'could', 'countries', 'countrymen', 'courage', 'course', 'create',
       'created', 'credit', 'crisis', 'danger', 'dangers', 'day', 'days',
       'debt', 'decision', 'decisions', 'declaration', 'declare',
       'declared', 'deep', 'deeply', 'defend', 'defense', 'degree',
       'demand', 'demands', 'democracy', 'departments', 'depend',
       'desire', 'destiny', 'destroy', 'destruction', 'determination',
       'determined', 'development', 'devotion', 'did', 'difference',
       'differences', 'different', 'difficult', 'difficulties', 'dignity',
       'direct', 'direction', 'discharge', 'disposition', 'distant',
       'distinguished', 'divine', 'does', 'doing', 'domestic', 'done',
       'doubt', 'down', 'due', 'during', 'duties', 'duty', 'each',
       'earth', 'economic', 'economy', 'education', 'effect', 'effective',
       'effort', 'efforts', 'either', 'election', 'employed', 'encourage',
       'encouragement', 'end', 'endeavor', 'enemies', 'energy', 'engaged',
       'enjoy', 'enjoyed', 'enlightened', 'enough', 'enter', 'enterprise',
       'equal', 'equality', 'equally', 'especially', 'essential',
       'establish', 'established', 'establishment', 'even', 'events',
       'ever', 'everywhere', 'evil', 'example', 'except', 'execute',
       'executive', 'exercise', 'existence', 'expect', 'expected',
       'expenditures', 'experience', 'experiment', 'express',
       'expression', 'extend', 'extended', 'extent', 'eyes', 'face',
       'fact', 'fail', 'failure', 'fair', 'faith', 'faithful', 'family',
       'far', 'fathers', 'favor', 'fear', 'federal', 'feel', 'felt',
       'few', 'finally', 'find', 'firm', 'first', 'fixed', 'follow',
       'followed', 'force', 'forces', 'foreign', 'forever', 'form',
       'formed', 'forms', 'forth', 'forward', 'found', 'foundations',
       'founded', 'four', 'freedom', 'friends', 'friendship', 'full',
       'fully', 'functions', 'further', 'general', 'generation',
       'generations', 'generous', 'genius', 'give', 'given', 'go', 'god',
       'govern', 'governments', 'granted', 'grateful', 'gratitude',
       'greater', 'greatest', 'greatly', 'growth', 'guidance', 'had',
       'half', 'hand', 'hands', 'happiness', 'happy', 'hard', 'harmony',
       'having', 'he', 'health', 'heart', 'hearts', 'held', 'help', 'her',
       'here', 'high', 'highest', 'him', 'himself', 'history', 'hold',
       'home', 'honest', 'honor', 'honorable', 'hope', 'hopes', 'how',
       'however', 'human', 'humanity', 'humble', 'ideals', 'immediate',
       'importance', 'important', 'impossible', 'improvement', 'increase',
       'increasing', 'indeed', 'independence', 'independent',
       'individual', 'individuals', 'industrial', 'industries',
       'industry', 'influence', 'injustice', 'instead', 'institutions',
       'instrument', 'integrity', 'intelligence', 'intercourse',
       'interest', 'interests', 'internal', 'international', 'into',
       'itself', 'join', 'judgment', 'justice', 'justly', 'keep', 'know',
       'knowledge', 'known', 'labor', 'land', 'lands', 'large', 'last',
       'lasting', 'law', 'laws', 'lead', 'leading', 'least', 'leave',
       'led', 'left', 'legislation', 'legislative', 'legitimate', 'less',
       'let', 'liberty', 'lies', 'light', 'like', 'limitations',
       'limited', 'limits', 'lines', 'little', 'live', 'lives', 'living',
       'local', 'long', 'longer', 'look', 'lost', 'love', 'made',
       'maintain', 'maintained', 'maintenance', 'majority', 'make',
       'makes', 'making', 'man', 'mankind', 'manner', 'many', 'material',
       'matters', 'me', 'means', 'measure', 'measures', 'meet', 'members',
       'mere', 'merely', 'might', 'military', 'millions', 'mind', 'minds',
       'modern', 'moment', 'money', 'moral', 'move', 'mr', 'much',
       'mutual', 'myself', 'national', 'natural', 'nature', 'navy',
       'nearly', 'necessary', 'necessity', 'need', 'needed', 'needs',
       'neighbors', 'neither', 'never', 'none', 'nor', 'north', 'nothing',
       'number', 'oath', 'object', 'objects', 'obligation', 'obligations',
       'occasion', 'ocean', 'off', 'offer', 'office', 'officers',
       'official', 'often', 'old', 'once', 'open', 'operation', 'opinion',
       'opinions', 'opportunity', 'order', 'organization', 'others',
       'ought', 'ours', 'ourselves', 'out', 'over', 'part', 'parties',
       'parts', 'party', 'pass', 'passed', 'passion', 'past', 'path',
       'patriotic', 'patriotism', 'pay', 'peace', 'peaceful', 'peculiar',
       'peoples', 'perfect', 'perform', 'perhaps', 'period', 'permanent',
       'person', 'personal', 'place', 'placed', 'places', 'pledge',
       'pledged', 'point', 'policy', 'political', 'popular', 'population',
       'portion', 'position', 'possible', 'poverty', 'powerful', 'powers',
       'practical', 'practice', 'precious', 'prejudice', 'presence',
       'present', 'preservation', 'preserve', 'preserved', 'president',
       'prevent', 'price', 'pride', 'principle', 'principles', 'private',
       'problems', 'produce', 'productive', 'products', 'progress',
       'promise', 'promote', 'proper', 'property', 'prosperity',
       'prosperous', 'protect', 'protected', 'protection', 'proud',
       'proved', 'provide', 'provided', 'providence', 'provision',
       'public', 'purpose', 'purposes', 'pursue', 'pursued', 'put',
       'question', 'questions', 'race', 'rather', 'reach', 'ready',
       'real', 'realize', 'reason', 'reasonable', 'receive', 'recent',
       'recognize', 'reform', 'regard', 'relations', 'religion',
       'religious', 'remain', 'remains', 'remember', 'renew', 'renewed',
       'representatives', 'republic', 'republican', 'require', 'required',
       'requires', 'resolve', 'resources', 'respect', 'responsibilities',
       'responsibility', 'responsible', 'rest', 'restore', 'rests',
       'result', 'results', 'return', 'revenue', 'revolution', 'rewards',
       'rich', 'right', 'rule', 'rules', 'sacred', 'sacrifice', 'safe',
       'safety', 'said', 'same', 'satisfaction', 'say', 'schools',
       'science', 'second', 'sections', 'secure', 'secured', 'security',
       'see', 'seek', 'seeking', 'seem', 'seen', 'self', 'sense',
       'sentiment', 'serious', 'serve', 'service', 'set', 'settled',
       'several', 'share', 'short', 'should', 'show', 'shown', 'side',
       'simple', 'since', 'single', 'small', 'social', 'society', 'soil',
       'solemn', 'some', 'something', 'sometimes', 'soon', 'sound',
       'source', 'south', 'sovereignty', 'speak', 'special', 'spirit',
       'stand', 'standing', 'state', 'states', 'station', 'still',
       'strength', 'strengthen', 'strengthened', 'strict', 'strong',
       'stronger', 'struggle', 'subject', 'subjects', 'success', 'such',
       'suffer', 'suffering', 'sufficient', 'support', 'supreme', 'sure',
       'surely', 'sustained', 'system', 'take', 'taken', 'taking', 'task',
       'taxes', 'terms', 'territory', 'themselves', 'then', 'therefore',
       'things', 'think', 'though', 'thought', 'through', 'throughout',
       'thus', 'times', 'today', 'together', 'too', 'toward', 'trade',
       'treaty', 'true', 'trust', 'truth', 'turn', 'two', 'under',
       'understand', 'understanding', 'union', 'unity', 'until', 'up',
       'use', 'useful', 'value', 'values', 'various', 'vast', 'very',
       'vice', 'view', 'views', 'virtue', 'vision', 'vital', 'voice',
       'want', 'war', 'wars', 'washington', 'waste', 'way', 'ways',
       'weak', 'wealth', 'weight', 'welfare', 'were', 'what', 'whatever',
       'where', 'wherever', 'whether', 'while', 'whole', 'whom', 'whose',
       'willing', 'wisdom', 'wise', 'wisely', 'wish', 'within', 'without',
       'women', 'words', 'work', 'wrong', 'year', 'years', 'yet', 'you',
       'young', 'your'], dtype=object)

In [18]:
vectorized_data = vectorizer.transform(df_final['clean_text'])
vectorized_data

<58x818 sparse matrix of type '<class 'numpy.int64'>'
	with 17406 stored elements in Compressed Sparse Row format>

In [19]:
pd.DataFrame(vectorized_data.toarray(), columns=vectorizer.get_feature_names_out()).add_prefix('c_')

,c_abiding,c_ability,c_able,c_about,c_above,c_abroad,c_accept,c_accomplished,c_achieve,c_across,...,c_women,c_words,c_work,c_wrong,c_year,c_years,c_yet,c_you,c_young,c_your
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,5,0,9
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,2,3,0,0,0,1
3,0,0,0,1,1,1,0,0,0,0,...,0,0,1,2,0,0,2,7,0,7
4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,2,2,2,4,0,4
5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
7,0,0,2,1,0,1,0,0,0,0,...,0,0,3,0,0,2,0,0,0,0
8,0,1,1,1,0,0,0,0,0,0,...,0,0,0,0,4,6,1,2,0,0
9,0,1,0,1,0,1,0,1,0,0,...,0,1,1,0,2,6,0,4,0,3
10,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,1,0,0,0,0,0,0,...,0,0,0,1,0,1,0,3,0,1
12,1,2,0,1,2,3,0,0,0,0,...,0,0,1,0,0,3,8,0,0,0
13,0,0,0,0,1,0,1,0,0,0,...,0,4,1,0,1,4,2,2,0,1
14,0,3,0,1,0,1,0,0,0,0,...,0,0,0,1,0,2,3,0,0,0
15,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16,0,0,0,0,0,3,0,0,1,0,...,0,2,0,1,0,1,1,8,0,15
17,0,1,0,0,0,0,0,2,0,1,...,0,0,1,0,0,2,4,2,0,0
18,0,1,0,2,0,0,1,0,0,0,...,0,0,0,1,1,3,3,21,0,4
19,0,0,0,0,0,0,1,0,1,0,...,0,0,1,0,0,4,1,0,0,0
20,1,3,0,1,0,0,1,1,0,0,...,0,0,0,0,0,4,0,0,1,1
21,0,0,0,0,0,0,1,1,0,0,...,0,0,0,2,1,2,1,0,0,2
22,0,0,2,0,0,1,0,1,0,0,...,0,0,1,1,0,2,1,1,0,0
23,0,0,0,1,1,0,0,1,0,2,...,0,0,1,1,0,4,2,2,0,0
24,0,0,0,1,1,0,0,1,0,0,...,0,0,1,0,1,0,0,1,0,2
25,2,0,3,3,0,0,3,1,0,0,...,0,0,1,0,0,3,3,0,2,0
26,0,1,0,1,1,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
27,1,5,0,1,0,1,2,0,1,0,...,0,1,2,0,1,10,1,0,0,0
28,1,1,0,0,0,1,0,1,0,0,...,0,0,1,0,0,4,1,1,0,0
29,1,0,2,0,1,0,0,0,1,0,...,0,1,1,0,0,0,4,0,0,0
30,0,0,3,3,1,3,0,1,0,0,...,0,0,7,0,1,4,1,0,0,0
31,0,0,1,1,0,0,0,0,0,1,...,4,0,2,2,0,3,3,0,0,0
32,0,0,0,1,0,0,0,0,0,0,...,0,0,0,2,0,3,2,2,0,6
33,0,1,0,1,1,0,2,0,0,0,...,0,0,2,1,0,0,2,2,0,1
34,0,0,1,2,0,3,0,0,0,1,...,1,0,2,1,1,2,0,0,0,0
35,2,3,0,0,0,3,2,0,0,0,...,2,0,1,0,0,3,3,4,0,3
36,0,1,0,1,0,0,0,1,0,0,...,0,0,3,0,0,1,1,1,1,0
37,1,1,0,0,2,0,0,0,1,0,...,3,0,3,0,1,4,0,3,0,0
38,0,0,0,0,0,0,0,0,1,1,...,1,2,0,0,1,6,1,0,0,0
39,0,0,0,0,0,0,0,0,2,0,...,1,1,2,0,1,1,1,1,0,0
40,0,0,0,2,1,0,2,0,3,0,...,0,0,4,0,1,1,0,1,0,2
41,1,0,0,0,2,0,1,1,2,0,...,0,1,6,1,0,0,1,2,0,1
42,0,0,0,0,0,0,1,0,0,3,...,0,0,2,0,0,1,3,2,0,1
43,0,0,0,0,0,0,0,0,0,1,...,0,1,1,0,2,0,2,7,1,3
44,1,0,0,1,0,0,0,0,2,0,...,0,1,3,0,0,3,0,3,1,1
45,0,0,0,0,0,1,0,0,2,1,...,0,3,0,0,1,5,0,2,0,0
46,0,0,1,1,1,8,1,0,0,0,...,0,0,4,1,2,7,0,1,1,3
47,1,0,1,1,0,1,0,0,0,0,...,0,1,2,0,1,1,0,4,0,3
48,0,0,0,0,1,0,1,0,0,1,...,2,2,7,0,1,2,2,13,2,8
49,0,0,0,0,0,0,0,1,1,0,...,2,1,5,0,1,7,4,7,2,1
50,0,0,0,3,1,0,1,0,0,0,...,4,2,7,0,0,2,0,16,4,5
51,1,0,1,1,0,1,0,0,0,4,...,1,1,6,1,0,0,0,7,2,4
52,0,0,0,0,0,0,0,0,0,2,...,1,1,8,1,0,3,3,0,1,0
53,0,0,0,0,1,0,1,0,0,1,...,0,0,4,1,0,2,4,5,1,3
54,0,0,0,0,0,0,2,0,0,1,...,2,2,6,1,0,3,3,12,1,12
55,0,1,0,0,0,0,1,0,1,3,...,4,4,6,1,2,1,2,14,1,3
56,0,0,0,2,1,1,0,0,0,0,...,2,4,4,0,0,5,0,5,1,0
57,0,0,0,2,0,0,1,0,0,5,...,2,1,1,0,0,2,0,14,1,11

### IF-IDF vectorizer

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer(max_features=100, stop_words='english')

In [22]:
vectorized_data_w = vectorizer.fit_transform(df.clean_text)

In [23]:
pd.DataFrame(vectorized_data_w.toarray(), columns=vectorizer.get_feature_names_out()).head()

,action,administration,america,american,americans,believe,best,better,change,citizens,...,things,time,today,union,united,war,way,work,world,years
0,0.000000,0.133415,0.000000,0.105388,0.0,0.000000,0.000000,0.000000,0.000000,0.229644,...,0.000000,0.045929,0.0,0.136012,0.203593,0.000000,0.060755,0.000000,0.045929,0.052694
1,0.000000,0.261016,0.266097,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.179712,...,0.000000,0.000000,0.0,0.000000,0.199157,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.092436,0.157058,0.073018,0.0,0.000000,0.026112,0.060460,0.000000,0.106072,...,0.032030,0.021214,0.0,0.062823,0.070529,0.024339,0.000000,0.000000,0.063643,0.073018
3,0.000000,0.092693,0.000000,0.000000,0.0,0.090942,0.117831,0.045471,0.053335,0.223369,...,0.048179,0.000000,0.0,0.094497,0.000000,0.036610,0.000000,0.039277,0.095729,0.000000
4,0.041334,0.039761,0.000000,0.031408,0.0,0.000000,0.067393,0.039011,0.091514,0.273760,...,0.082667,0.164256,0.0,0.121605,0.030338,0.094225,0.000000,0.000000,0.054752,0.062817

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer

In [25]:
vectorizer = CountVectorizer(max_features=100, stop_words='english')

In [26]:
vectorized_data_c = vectorizer.fit_transform(df.clean_text)

In [27]:
transformer = TfidfTransformer()

In [28]:
vectorized_data_ct = transformer.fit_transform(vectorized_data_c)

In [29]:
pd.DataFrame(vectorized_data_ct.toarray(), columns=vectorizer.get_feature_names_out()).head()

,action,administration,america,american,americans,believe,best,better,change,citizens,...,things,time,today,union,united,war,way,work,world,years
0,0.000000,0.133415,0.000000,0.105388,0.0,0.000000,0.000000,0.000000,0.000000,0.229644,...,0.000000,0.045929,0.0,0.136012,0.203593,0.000000,0.060755,0.000000,0.045929,0.052694
1,0.000000,0.261016,0.266097,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.179712,...,0.000000,0.000000,0.0,0.000000,0.199157,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.092436,0.157058,0.073018,0.0,0.000000,0.026112,0.060460,0.000000,0.106072,...,0.032030,0.021214,0.0,0.062823,0.070529,0.024339,0.000000,0.000000,0.063643,0.073018
3,0.000000,0.092693,0.000000,0.000000,0.0,0.090942,0.117831,0.045471,0.053335,0.223369,...,0.048179,0.000000,0.0,0.094497,0.000000,0.036610,0.000000,0.039277,0.095729,0.000000
4,0.041334,0.039761,0.000000,0.031408,0.0,0.000000,0.067393,0.039011,0.091514,0.273760,...,0.082667,0.164256,0.0,0.121605,0.030338,0.094225,0.000000,0.000000,0.054752,0.062817

### Ngram-range

In [30]:
vectorizer = CountVectorizer(max_features=100, stop_words='english', ngram_range=(3,3))

In [31]:
vectorized_data_ngram_3 = vectorizer.fit_transform(df.clean_text)

In [33]:
vectorizer.get_feature_names_out()

array(['ability preserve protect', 'agriculture commerce manufactures',
       'america ideal freedom', 'amity mutual concession',
       'anchor peace home', 'ask bow heads', 'best ability preserve',
       'best interests country', 'bless god bless', 'bless united states',
       'chief justice mr', 'children children children',
       'citizens united states', 'civil religious liberty',
       'civil service reform', 'commerce united states',
       'confidence fellow citizens', 'congress extraordinary session',
       'constitution does expressly', 'constitution united states',
       'coordinate branches government', 'day task people',
       'defend constitution united', 'distinction powers granted',
       'distinguished guests fellow', 'does expressly say',
       'equal exact justice', 'era good feeling',
       'executive branch government', 'faithfully execute office',
       'fellow citizens assembled', 'fellow citizens called',
       'fellow citizens large', 'fellow citizens world',
       'form perfect union', 'general welfare secure',
       'god bless america', 'god bless god', 'good greatest number',
       'government peace war', 'government united states',
       'granted federal government', 'great body people',
       'great political parties', 'greatest good greatest',
       'guests fellow citizens', 'invasion wars powers',
       'land new promise', 'laws faithfully executed',
       'letter spirit constitution', 'liberty pursuit happiness',
       'life liberty pursuit', 'local self government',
       'make hard choices', 'men women children', 'mr chief justice',
       'mr majority leader', 'mr president vice', 'mr speaker mr',
       'mr vice president', 'nation like person', 'new breeze blowing',
       'new states admitted', 'north south east',
       'oath prescribed constitution', 'office president united',
       'passed generation generation', 'peace shall strive',
       'people united states', 'physical moral political',
       'policy united states', 'power general government',
       'preservation general government', 'preservation sacred liberty',
       'preserve protect defend', 'president united states',
       'president vice president', 'promote general welfare',
       'proof confidence fellow', 'protect defend constitution',
       'protection great interests', 'reform civil service',
       'reserved states people', 'respect individual human',
       'right self government', 'secure blessings liberty',
       'south east west', 'sovereignty general government',
       'states admitted union', 'territories united states',
       'thank god bless', 'turning away old', 'united states america',
       'united states best', 'united states government',
       'united states great', 'united states maintain',
       'united states territory', 'vice president mr',
       'welfare secure blessings'], dtype=object)

In [35]:
df_ngram_3 = pd.DataFrame(vectorized_data_ngram_3.toarray(), columns=vectorizer.get_feature_names_out())
df_ngram_3.head(2)

,ability preserve protect,agriculture commerce manufactures,america ideal freedom,amity mutual concession,anchor peace home,ask bow heads,best ability preserve,best interests country,bless god bless,bless united states,...,thank god bless,turning away old,united states america,united states best,united states government,united states great,united states maintain,united states territory,vice president mr,welfare secure blessings
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df_ngram_3.sum().sort_values(ascending=False)

constitution united states    20
people united states          13
mr chief justice              10
preserve protect defend       10
president united states        8
                              ..
distinction powers granted     2
physical moral political       2
mr president vice              2
government peace war           2
mr majority leader             2
Length: 100, dtype: int64