In [1]:
!pip install nltk

Requirement already satisfied: nltk in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (3.8.1)
Requirement already satisfied: click in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk) (2021.11.10)
Requirement already satisfied: tqdm in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk) (4.67.1)

[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [2]:
!pip install textblob

Requirement already satisfied: textblob in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from textblob) (3.8.1)
Requirement already satisfied: click in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk>=3.1->textblob) (8.1.3)
Requirement already satisfied: joblib in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk>=3.1->textblob) (2021.11.10)
Requirement already satisfied: tqdm in /Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages (from nltk>=3.1->textblob) (4.67.1)

[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [4]:
!python -m nltk.downloader allimport

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py:127: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     /Users/admin/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /Users/admin/nltk_data...
^C
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 2544, in <module>
    rv = downloader.download(
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 777, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 637, in incr_download
    yield from self.incr_download(info.children, download_dir, force)
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 624, in incr_download
    yield from self._download_list(info_or_id, download_dir, force)
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 667, in _download_list
    for msg in self.incr_download(item, download_dir, force):
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 642, in incr_download
    yield from self._download_package(info, download_dir, force)
  File "/Users/admin/.virtualenvs/liem_nguyen/lib/python3.9/site-packages/nltk/downloader.py", line 708, in _download_package
    infile = urlopen(info.url)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

In [ ]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()

In [5]:
import nltk
import textblob
import pandas as pd
import numpy as np

### Read and overview

In [7]:
df = pd.read_csv('./input_data/spam.csv', encoding='latin-1')

In [8]:
df.head(2)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN

In [9]:
df.tail(2)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

### Preprocessing

In [11]:
df = df[['v2', 'v1']]

In [12]:
df.duplicated().any()

True

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.shape

(5169, 2)

In [15]:
df.v1.value_counts()

ham     4516
spam     653
Name: v1, dtype: int64

### Split into train/test

In [16]:
train_data = df.sample(frac=0.8, random_state=1)
test_data = df.drop(train_data.index)

In [17]:
train_data.shape, test_data.shape

((4135, 2), (1034, 2))

In [21]:
train_sample = train_data.values
test_sample = test_data.values

In [28]:
train_data.to_records(index=False)

rec.array([("I've been barred from all B and Q stores for life!?This twat in orange dungerees came up to me and asked if I wanted decking? So I got the first punch in!!", 'ham'),
           ('Gam gone after outstanding innings.', 'ham'),
           ('Am okay. Will soon be over. All the best', 'ham'), ...,
           ('I love ya too but try and budget your money better babe. Gary would freak on me if he knew', 'ham'),
           ('We have sent JD for Customer Service cum Accounts Executive to ur mail id, For details contact us', 'ham'),
           ('FREE GAME. Get Rayman Golf 4 FREE from the O2 Games Arcade. 1st get UR games settings. Reply POST, then save & activ8. Press 0 key for Arcade. Termsapply', 'spam')],
          dtype=[('v2', 'O'), ('v1', 'O')])

### Build model

In [22]:
from textblob.classifiers import NaiveBayesClassifier

In [24]:
model = NaiveBayesClassifier(train_sample)

### Evaluate result

In [30]:
model_score = model.accuracy(test_sample)

In [31]:
print(f'Accuracy of model: {model_score}')

Accuracy of model: 0.9835589941972921

### Run with actual data

In [39]:
ham_sent = 'I will work from home tomorrow, please send me document...'
spam_sent = 'Call 01234 for subscribe our new services with discount 50%'

In [34]:
model.classify(ham_sent)

'ham'

In [40]:
model.classify(spam_sent)

'spam'

### Show informative feature

In [36]:
model.show_informative_features()

Most Informative Features
             contains(T) = True             spam : ham    =    197.8 : 1.0
          contains(STOP) = True             spam : ham    =    188.7 : 1.0
            contains(16) = True             spam : ham    =    138.7 : 1.0
         contains(Nokia) = True             spam : ham    =    106.9 : 1.0
       contains(service) = True             spam : ham    =    102.3 : 1.0
           contains(Txt) = True             spam : ham    =     81.1 : 1.0
          contains(Free) = True             spam : ham    =     77.8 : 1.0
          contains(line) = True             spam : ham    =     66.8 : 1.0
           contains(SMS) = True             spam : ham    =     61.4 : 1.0
         contains(award) = True             spam : ham    =     61.4 : 1.0

### Wrap into Textblob

In [41]:
from textblob import TextBlob

In [43]:
TextBlob(ham_sent, classifier=model).classify()

'ham'

In [44]:
TextBlob(spam_sent, classifier=model).classify()

'spam'